language: ruby
rvm:
  - 1.8.7
before_install:
  - "gem uninstall bundler"
  - "gem install bundler --version=1.0.0"
before_script:
  - "rake create_a_secret"
  - "cp config/database.yml.example config/database.yml"
  - "gem install mysql"
  - "rake db:create"
  - "rake db:schema:load"
