# options -------------------------------------------
# searchd log file:: log/searchd.log
# query log file::   log/searchd.query.log
# pid file::         log/searchd.#{environment}.pid
# searchd files::    db/sphinx/#{environment}/
# allow star::       false

development:
  config_file: config/sphinx/development.conf
  port: 3312
  address: localhost
  morphology: stem_en
  
test:
  config_file: config/sphinx/test.conf
  port: 3313
  address: localhost
  morphology: stem_en

production:
  config_file: /usr/apps/crabgrass/shared/config/sphinx/production.conf
  pid_file: /usr/apps/crabgrass/shared/tmp/searchd.pid
  searchd_file_path: /usr/apps/crabgrass/shared/db/sphinx
  searchd_log_file: /usr/apps/crabgrass/shared/log/sphinx.log
  query_log_file: /usr/apps/crabgrass/shared/log/sphinx.query.log
  port: 3312
  address: localhost
  morphology: stem_en

